Add commands to list, clone and remove environments

diff --git a/bin/borg-env b/bin/borg-env
--- a/bin/borg-env
+++ b/bin/borg-env
@@ -1,11 +1,7 @@
 #!/bin/bash
-# TODO: delete an environment config
-# TODO: clone an environment
-# TODO: allow creation of new environments using the default config as template
 # TODO: MAYBE add a template environment file that is copied to new environments
-# TODO: list environments
 # TODO: remove "Usage" from commands
-# TODO: exit conde on "Usage" output of subcommands?
+# TODO: exit code on "Usage" output of subcommands?
 # TODO: reload current env after edit
 
 # Treat unset variables as an error.
@@ -69,6 +65,17 @@ HELP="
       the currently active config. To edit the default variables use
       \"${DEFAULT_ENV}\" as name.
 
+    clone <env-name|-> <new-env-name>
+      Clone an environment config to a new name. Pass '-' as name to clone the
+      currently active config.
+
+    remove <env-name>
+      Delete an environment. This can't be undone but luckily, if you use this
+      tool, you are likely going to have a backup anyways ;)
+
+    list
+      List all environments.
+
     reload
       NOT IMPLEMENTED YET
       Reload the current environment. Useful when the config has been changed
@@ -111,9 +118,10 @@ main() {
             echo "">&2
             echo "  SORRY: This feature is not implemented yet." >&2
             echo "">&2
-            exit 1
+            EXIT 1
             ;;
-        'create'|'edit'|'reload'|'set'|'run'|'show')
+        'create'|'edit'|'clone'|'remove'|\
+        'list'|'reload'|'set'|'run'|'show')
             setup
             cmd_${cmd} "$@"
             ;;
@@ -152,10 +160,11 @@ cmd_create() {
     fi
 
     touch "$file" || EXIT_ERROR 1 "Could not create environment file \"${file}\"!"
-    edit "$file"
-
     echo "Created new environment \"${name}\"."
+
+    edit "$file"
 }
+
 
 cmd_edit() {
     local name="$(get_env_name "$1")"
@@ -174,6 +183,80 @@ cmd_edit() {
     fi
 
     edit "$file"
+}
+
+
+cmd_clone() {
+    local name="$(get_env_name "$1")"
+    local new_name="$2"
+    local file="$(make_env_file_name "${name}")"
+    local new_file="$(make_env_file_name "${new_name}")"
+
+    if [[ -z $name ]] || [[ -z $new_name ]]; then
+        echo "
+  Usage:
+    ${SCRIPT_NAME} clone <env-name|-> <new-env-name>
+"
+        EXIT
+    fi
+
+    if [[ ! -f $file ]]; then
+        EXIT_ERROR 1 "Environment \"${name}\" does not exist. Use \`create\` to create it."
+    fi
+
+    # TODO: These checks are the same as for creation. Refactor this!
+    if ! [[ $new_name =~ ^[a-zA-Z0-9_.-]+$ ]]; then
+        EXIT_ERROR 1 "The environment name is invalid. Allowed characters are: 'a-z', 'A-Z', '0-9', '_', '.', '-'"
+    fi
+
+    if [[ $new_name =~ ^\. ]]; then
+        EXIT_ERROR 1 "The environment name must not start with a dot!"
+    fi
+
+    if [[ -f $new_file ]]; then
+        EXIT_ERROR 1 "An environment with that name already exists! Use \`edit\` to edit it."
+    fi
+
+    cp "$file" "$new_file" || EXIT_ERROR 1 "Could not clone environment file \"${file}\" to \"${new_file}\"!"
+    echo "Cloned new environment \"${name}\"."
+
+    edit "$new_file"
+}
+
+
+cmd_remove() {
+    local name="$1"
+    local file="$(make_env_file_name "${name}")"
+
+    if [[ ! -f $file ]]; then
+        EXIT_ERROR 1 "Environment \"${name}\" does not exist."
+    fi
+
+    echo "Do you really want to remove the environment \"${name}\"?" >&2
+    read -p "(Type uppercase yes to confirm): " confirm
+
+    if [[ $confirm != 'YES' ]]; then
+        EXIT
+    fi
+
+    rm "$file"
+    echo "Deleted environment \"${name}\"."
+}
+
+
+cmd_list() {
+    local list=($(ls "$ENVIRONMENTS"))
+
+    for env in ${list[@]}; do
+        env="${env/%.env/}"
+        active=''
+
+        if [[ ${BORG_ENV:-} == $env ]]; then
+            active='*'
+        fi
+
+        echo " ${active:- } ${env}"
+    done
 }
 
 
